[package]
name = "rust-ttest-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.17.1"
npy = "0.4.0"
ndarray = "0.16.1"
